import blacklogo from "../public/HomeImg/blacklogo.png"
import black from "../public/HomeImg/black.png"
import whitelogo from "../public/HomeImg/whitelogo.png"
import male from "../public/HomeImg/male.jpg"
import male1 from "../public/HomeImg/male1.jpg"
import female from "../public/HomeImg/female.jpg"
import AwardsOne from "../public/HomeImg/AwardsOne.svg"
import AwardsTwo from "../public/HomeImg/AwardsTwo.svg"
import AwardsThree from "../public/HomeImg/AwardsThree.svg"
import AwardsFour from "../public/HomeImg/AwardsFour.png"
import AwardsFive from "../public/HomeImg/AwardsFive.svg"
import AwardsSix from "../public/HomeImg/AwardsSix.svg"
import AwardsSeven from "../public/HomeImg/AwardsSeven.svg"
import m from "../public/HomeImg/m.jpg"
import be from "../public/HomeImg/be.png"
import top from "../public/HomeImg/top.png"
import whatsapp from "../public/HomeImg/whatsapp.svg"
import gmail from "../public/HomeImg/gmail.svg"

export { blacklogo, whitelogo, AwardsOne, AwardsTwo, AwardsThree, AwardsFour, AwardsFive, AwardsSix, AwardsSeven, m, be, top, male, male1, female, black, whatsapp, gmail }