import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navebar from "@/components/comman/Navbar/Navbar";
import Footer from "@/components/comman/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Codem Infotech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navebar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
